apt-get install curl
apt-get install libboost-all-dev
apt-get install libboost-python-dev
apt-get install libcurl4-openssl-dev
apt-get install libeigen3-dev
apt-get install libgeographic-dev
apt-get install libglew-dev
apt-get install libglfw3-dev
apt-get install libgtest-dev
apt-get install libgtk2.0-dev
apt-get install libjsoncpp-dev
apt-get install libjsoncpp1
apt-get install libpcap0.8-dev
apt-get install libpcl-apps1.8
apt-get install libpcl-common1.8
apt-get install libpcl-dev
apt-get install libpcl-features1.8
apt-get install libpcl-filters1.8
apt-get install libpcl-io1.8
apt-get install libpcl-kdtree1.8
apt-get install libpcl-keypoints1.8
apt-get install libpcl-ml1.8
apt-get install libpcl-octree1.8
apt-get install libpcl-outofcore1.8
apt-get install libpcl-people1.8
apt-get install libpcl-recognition1.8
apt-get install libpcl-registration1.8
apt-get install libpcl-sample-consensus1.8
apt-get install libpcl-search1.8
apt-get install libpcl-segmentation1.8
apt-get install libpcl-stereo1.8
apt-get install libpcl-surface1.8
apt-get install libpcl-tracking1.8
apt-get install libpcl-visualization1.8
apt-get install libpugixml-dev
apt-get install libqt5core5a
apt-get install libtclap-dev
apt-get install libyaml-cpp-dev
apt-get install python-matplotlib
apt-get install python-rospkg
apt-get install python-setuptools
apt-get install python-shapely
apt-get install python-yaml
apt-get install python3-click
apt-get install python3-dev
apt-get install python3-nose
apt-get install python3-rospkg-modules
apt-get install python3-venv
apt-get install qtbase5-dev
apt-get install ros-melodic-actionlib
apt-get install ros-melodic-actionlib-msgs
apt-get install ros-melodic-angles
apt-get install ros-melodic-autoware-lanelet2-msgs
apt-get install ros-melodic-autoware-msgs
apt-get install ros-melodic-bfl
apt-get install ros-melodic-calibration-msgs
apt-get install ros-melodic-camera-calibration
apt-get install ros-melodic-camera-calibration-parsers
apt-get install ros-melodic-camera-info-manager
apt-get install ros-melodic-can-msgs
apt-get install ros-melodic-catkin
apt-get install ros-melodic-catkin-virtualenv
apt-get install ros-melodic-cmake-modules
apt-get install ros-melodic-code-coverage
apt-get install ros-melodic-cv-bridge
apt-get install ros-melodic-depth-image-proc
apt-get install ros-melodic-diagnostic-msgs
apt-get install ros-melodic-diagnostic-updater
apt-get install ros-melodic-dynamic-reconfigure
apt-get install ros-melodic-eigen-conversions
apt-get install ros-melodic-fake-localization
apt-get install ros-melodic-gazebo-ros
apt-get install ros-melodic-gazebo-ros-pkgs
apt-get install ros-melodic-geometry-msgs
apt-get install ros-melodic-gps-common
apt-get install ros-melodic-image-geometry
apt-get install ros-melodic-image-proc
apt-get install ros-melodic-image-publisher
apt-get install ros-melodic-image-rotate
apt-get install ros-melodic-image-transport
apt-get install ros-melodic-image-view
apt-get install ros-melodic-joy
apt-get install ros-melodic-jsk-rviz-plugins
apt-get install ros-melodic-lanelet2-core
apt-get install ros-melodic-lanelet2-examples
apt-get install ros-melodic-lanelet2-io
apt-get install ros-melodic-lanelet2-maps
apt-get install ros-melodic-lanelet2-projection
apt-get install ros-melodic-lanelet2-python
apt-get install ros-melodic-lanelet2-routing
apt-get install ros-melodic-lanelet2-traffic-rules
apt-get install ros-melodic-lanelet2-validation
apt-get install ros-melodic-message-filters
apt-get install ros-melodic-message-generation
apt-get install ros-melodic-message-runtime
apt-get install ros-melodic-mrt-cmake-modules
apt-get install ros-melodic-nav-msgs
apt-get install ros-melodic-nodelet
apt-get install ros-melodic-nodelet-topic-tools
apt-get install ros-melodic-pcl-conversions
apt-get install ros-melodic-pcl-ros
apt-get install ros-melodic-pluginlib
apt-get install ros-melodic-qpoases-vendor
apt-get install ros-melodic-robot-localization
apt-get install ros-melodic-robot-state-publisher
apt-get install ros-melodic-ros-environment
apt-get install ros-melodic-rosbag
apt-get install ros-melodic-rosbash
apt-get install ros-melodic-rosconsole
apt-get install ros-melodic-roscpp
apt-get install ros-melodic-roslaunch
apt-get install ros-melodic-roslib
apt-get install ros-melodic-roslint
apt-get install ros-melodic-rospy
apt-get install ros-melodic-rostest
apt-get install ros-melodic-rosunit
apt-get install ros-melodic-rviz
apt-get install ros-melodic-sensor-msgs
apt-get install ros-melodic-socketcan-bridge
apt-get install ros-melodic-socketcan-interface
apt-get install ros-melodic-std-msgs
apt-get install ros-melodic-std-srvs
apt-get install ros-melodic-stereo-image-proc
apt-get install ros-melodic-stereo-msgs
apt-get install ros-melodic-tf
apt-get install ros-melodic-tf2
apt-get install ros-melodic-tf2-eigen
apt-get install ros-melodic-tf2-geometry-msgs
apt-get install ros-melodic-tf2-ros
apt-get install ros-melodic-topic-tools
apt-get install ros-melodic-urdf
apt-get install ros-melodic-velodyne-driver
apt-get install ros-melodic-velodyne-gazebo-plugins
apt-get install ros-melodic-velodyne-laserscan
apt-get install ros-melodic-velodyne-msgs
apt-get install ros-melodic-velodyne-pointcloud
apt-get install ros-melodic-visualization-msgs
apt-get install ros-melodic-xacro
apt-get install virtualenv
apt-get install wget
rosdep-source install https://raw.githubusercontent.com/dragandbot/pylon-ros-camera/pylon6-dev/pylon_camera/rosdep/pylon_sdk.rdmanifest
